name: Deploy to GitHub Pages

on:
  push:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: rustup target add wasm32-unknown-unknown
      - run: cargo build --target wasm32-unknown-unknown --release
      - run: mv .github/public/ public/
      - run: cp target/wasm32-unknown-unknown/release/rusty-hitman.wasm public/
      - run: cp -R assets/ public/

      - name: Publish current workdir to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3
        with:
          source-directory: public
          target-branch: gh_pages
